baseURL = 'https://blog.seekella.com/'
languageCode = 'en'
theme = "hugo-bearcub"
defaultContentLanguage = 'en'
enableRobotsTXT = true

[languages]
  [languages.ja]
    title = '無名'
    author = '山田太郎'
    copyright = '© 2025 山田太郎'
    languageName = '日本語'
    weight = 2
    contentDir = 'content/ja'
    languageCode = 'ja'
    [languages.ja.params]
      madeWith = "[ᕦʕ •ᴥ•ʔᕤ](https://github.com/clente/hugo-bearcub) で作られました"
      dateFormat = "2006年1月2日"
  [languages.zh]
    title = '無名'
    author = '张三'
    copyright = '© 2025 张三'
    languageName = '中文 '
    weight = 3
    contentDir = 'content/zh'
    languageCode = 'zh'
    [languages.zh.params]
      madeWith = "由 [ᕦʕ •ᴥ•ʔᕤ](https://github.com/clente/hugo-bearcub) 构建"
      dateFormat = "2006年1月2日"
  [languages.en]
    title = 'NoNAME'
    author = 'John Doe'
    copyright = '© 2025 John Doe'
    languageName = 'English'
    weight = 1
    contentDir = 'content/en'
    languageCode = 'en'
    [languages.en.params]
      madeWith = "Made with [ᕦʕ •ᴥ•ʔᕤ](https://github.com/clente/hugo-bearcub)"
      dateFormat = "January 2, 2006"
  [languages.ko]
    title = '이름없음'
    author = '홍길동'
    copyright = '© 2025 홍길동'
    languageName = '한국어'
    weight = 4
    contentDir = 'content/ko'
    languageCode = 'ko'
    [languages.ko.params]
      madeWith = "이 사이트는 [ᕦʕ •ᴥ•ʔᕤ](https://github.com/clente/hugo-bearcub)로 만들어졌습니다"
      dateFormat = "2006년 1월 2일"
[params]
  themeStyle = "herman"
  [params.author]
    email = "john.doe@seekella.com"
